#!/bin/bash


PAK="echo <html><body><table><thead><tr><th>login</th><th>home</th><th>shell</th></t$></thead><tbody>"
PAK+='cat /etc/passwd | awk -F':' {print "<tr><td>" $1 "</td><td>" $6 "</td><td>" $7 "</td></tr>"}'
PAK+="echo </tbody></table></body></html>"

echo $PAK > index.html
